### ISSUE TITLE
Stuck in google sign in

### ISSUE THREAD

**Issue by hussmartinez** [EliteAndroidApps/WhatsApp-GD-Extractor#12]
When I get :

Error=NeedsBrowser
Url=https://accounts.google.com/signin/continue?.........................
ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.

-----
I open the link, sign in and it gets stuck with "One moment please" message from google...

![screenshot from 2017-11-12 22-25-38](https://user-images.githubusercontent.com/22710836/32703014-7a1f9c2a-c7f8-11e7-9f81-fec393f90b89.png)

**Comment by chavanrohan111** [comment]
just need to login to your gmail account

**Comment by hussmartinez** [comment]
The problem happens when i try to login, it gets stuck with that image forever.
I thought maybe google updated something and then the script doesn't work anymore.
Tried with different browsers, OSes & google accounts and same situation happens.
It works with u?

**Comment by chavanrohan111** [comment]
if it is not working then just copy this link and past it on your browser 
https://accounts.google.com/b/0/DisplayUnlockCaptcha
and click on continue button and then try the script which you are running

**Comment by hussmartinez** [comment]
thanks, now it works!!!

**Comment by vitormarcelino** [comment]
I have the same error, I already tested on several devices, different browsers and recaptcha unlock and continue with the error.  I'm using Ubuntu 18.04.
