### ISSUE TITLE
Failed in Conection

### ISSUE THREAD

**Issue by spclover** [EliteAndroidApps/WhatsApp-GD-Extractor#8]
The system was working fine until a few weeks ago. Now I can't download backups from any of my accounts. I tried with some friends accounts and the problem persists.

The error is the usual "Error= BadAuthentication", but I was able to make it work anyway just by trying about 10 times getting that message. The eleventh one, worked fine.

But now is only the "Error= BadAuthentication" always, after about 100 tries.

Maybe Google made some blocking? Can somebody, please, confirm that this script is still working?

Truly thanks. It's a so useful resource.

**Comment by ViperCode7** [comment]
Yeah, you should open your eyes and read before posting. The issue is already fixed.

**Comment by spclover** [comment]
@ViperCode7 Yeah, and I can post anything I want, thanks. And just because there is always stupid people like you that doesn't help. Like all the people here weren't noobs at the beggining...

**Comment by ViperCode7** [comment]
Pointing out that out of 2 open issues, one is what you need, and alerting you that your issue is already solved makes me the stupid one? And how about me posting a fix there, was that not help? There's a saying, people who get insulted easily tend to be idiots. I'm sorry for you!
